services:
  db:
    image: postgres:alpine
    container_name: url_shortener_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: olymahmudmugdho/url-shortener
    container_name: url_shortener_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_SSLMODE: disable
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

volumes:
  postgres_data:
